=== apache/tajo/tajo-catalog/tajo-catalog-server/src/main/resources/schemas/DBMSSchemaDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<schema targetNamespace="http://tajo.apache.org/catalogstore" 
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://tajo.apache.org/catalogstore">

    <simpleType name="DatabaseObjectsType">
    	<annotation>
    		<documentation>
    			PostgreSQL defines its database objects in this
    			following link
    			(http://www.postgresql.org/docs/9.3/static/server-programming.html).
    			We also need to define these objects type to support in
    			our catalog stores.
    		</documentation>
    	</annotation>
    	<restriction base="string">
    		<enumeration value="table"></enumeration>
    		<enumeration value="view"></enumeration>
    		<enumeration value="function"></enumeration>
    		<enumeration value="operator"></enumeration>
    		<enumeration value="data"></enumeration>
    		<enumeration value="domain"></enumeration>
    		<enumeration value="trigger"></enumeration>
    		<enumeration value="rule"></enumeration>
    		<enumeration value="sequence"></enumeration>
    		<enumeration value="index"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="ExecutionOrderType">
    	<restriction base="int">
    		<minInclusive value="0"></minInclusive>
    	</restriction>
    </simpleType>
    
    <complexType name="ObjectsType">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<element name="Object" type="tns:ObjectType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ObjectType">
    	<sequence>
    		<element name="sql" type="tns:SqlType" minOccurs="1"></element>
    	</sequence>
    	<attributeGroup ref="tns:ObjectAttributeGroup"></attributeGroup>
    </complexType>
    
    <attributeGroup name="ObjectAttributeGroup">
        <attribute name="name" type="tns:ObjectNameType" use="required"></attribute>
        <attribute name="order" type="tns:ExecutionOrderType"></attribute>
    	<attribute name="dependsOn" type="tns:ObjectNameType"></attribute>
    	<attribute name="type" type="tns:DatabaseObjectsType"
    		use="required">
    	</attribute>
    </attributeGroup>

    <simpleType name="SqlType">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="PatchesType">
    	<sequence>
    		<element name="patch" type="tns:PatchType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="BaseSchemaType">
    	<sequence>
    		<element name="objects" type="tns:ObjectsType" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
        <attributeGroup ref="tns:BaseSchemaAttributeGroup"></attributeGroup>
    </complexType>

    <attributeGroup name="BaseSchemaAttributeGroup">
        <attribute name="schemaname" type="tns:SchemaNameType" use="optional"></attribute>
        <attribute name="version" type="tns:SchemaVersionType"
    		use="required">
    	</attribute>
    </attributeGroup>

    <simpleType name="SchemaVersionType">
    	<restriction base="int">
    		<minInclusive value="0"></minInclusive>
    	</restriction>
    </simpleType>

    <complexType name="PatchType">
    	<sequence>
    		<element name="objects" type="tns:ObjectsType" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
        <attributeGroup ref="tns:PatchAttributeGroup"></attributeGroup>
    </complexType>
    
    <simpleType name="ObjectNameType">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    	</restriction>
    </simpleType>

    <simpleType name="SchemaNameType">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    	</restriction>
    </simpleType>

    <attributeGroup name="PatchAttributeGroup">
    	<attribute name="priorVersion" type="tns:SchemaVersionType"
    		use="required">
    	</attribute>
    	<attribute name="nextVersion" type="tns:SchemaVersionType"></attribute>
    </attributeGroup>

    <complexType name="CatalogStoreType">
    	<sequence>
    		<element name="base" type="tns:BaseSchemaType" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="patches" type="tns:PatchesType" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="existQueries" type="tns:ExistsQueriesType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="dropStatements" type="tns:DropStatementsType" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="store" type="tns:CatalogStoreType"></element>

    <complexType name="ExistsQueryType">
    	<sequence>
    		<element name="sql" type="tns:SqlType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="type" type="tns:DatabaseObjectsType"
    		use="required">
    	</attribute>
    </complexType>

    <complexType name="ExistsQueriesType">
    	<sequence>
    		<element name="existQuery" type="tns:ExistsQueryType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="DropStatementsType">
    	<sequence>
    		<element name="dropStatement" type="tns:DropStatementType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="DropStatementType">
    	<sequence>
    		<element name="sql" type="tns:SqlType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="type" type="tns:DatabaseObjectsType"
    		use="required">
    	</attribute>
    </complexType>
</schema>

=== apache/tajo/tajo-catalog/tajo-catalog-server/src/test/resources/schemas/derbytest/mergetest/base_version_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<tns:store xmlns:tns="http://tajo.apache.org/catalogstore" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://tajo.apache.org/catalogstore ../../../../../main/resources/schemas/DBMSSchemaDefinition.xsd ">
	<tns:base version="1">
		<tns:objects>
			<tns:Object order="0" type="table" name="TESTTABLE1">
				<tns:sql><![CDATA[CREATE TABLE TESTTABLE1 (COL1 INT, COL2 VARCHAR(20))]]></tns:sql>
			</tns:Object>
			<tns:Object order="1" type="index" name="TESTINDEX1" dependsOn="TESTTABLE1">
				<tns:sql><![CDATA[CREATE INDEX TESTINDEX1 ON TESTTABLE1 (COL1)]]></tns:sql>
			</tns:Object>
			<tns:Object order="2" type="table" name="TESTTABLE2">
				<tns:sql><![CDATA[CREATE TABLE TESTTABLE2 (COL1 INT, COL2 VARCHAR(10))]]></tns:sql>
			</tns:Object>
		</tns:objects>
	</tns:base>
</tns:store>

=== apache/tajo/tajo-catalog/tajo-catalog-server/src/test/resources/schemas/derbytest/loadtest/derby.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<tns:store xmlns:tns="http://tajo.apache.org/catalogstore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tajo.apache.org/catalogstore ../DBMSSchemaDefinition.xsd ">
	<tns:base version="2" schemaname="tajo">
		<tns:objects>
			<tns:Object order="0" type="table" name="META">
				<tns:sql><![CDATA[CREATE TABLE META (VERSION INT NOT NULL)]]></tns:sql>
			</tns:Object>
			<tns:Object order="1" type="table" name="TABLESPACES">
				<tns:sql><![CDATA[
				CREATE TABLE TABLESPACES (
  				SPACE_ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  				SPACE_NAME VARCHAR(128) NOT NULL CONSTRAINT SPACE_UNIQUE UNIQUE,
  				SPACE_HANDLER VARCHAR (1024) DEFAULT 'HDFS',
  				SPACE_URI VARCHAR (4096) NOT NULL,
  				CONSTRAINT C_SPACE_PK PRIMARY KEY (SPACE_ID)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="2" type="table" name="DATABASES_">
				<tns:sql><![CDATA[
				CREATE TABLE DATABASES_ (
  				DB_ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  				DB_NAME VARCHAR(128) NOT NULL CONSTRAINT DB_NAME_UNIQ UNIQUE,
  				SPACE_ID INT NOT NULL REFERENCES TABLESPACES (SPACE_ID),
  				CONSTRAINT DATABASES_PK PRIMARY KEY (DB_ID)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="3" type="index" name="IDX_DATABASE_DB_ID" dependsOn="DATABASES_">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX idx_database_db_id on DATABASES_ (DB_ID)]]></tns:sql>
			</tns:Object>
			<tns:Object order="4" type="table" name="TABLES">
				<tns:sql><![CDATA[
				CREATE TABLE TABLES (
  				TID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  				DB_ID int NOT NULL REFERENCES DATABASES_ (DB_ID),
  				TABLE_NAME VARCHAR(128) NOT NULL,
  				TABLE_TYPE VARCHAR(128) NOT NULL,
  				PATH VARCHAR(4096),
  				STORE_TYPE CHAR(16),
  				CONSTRAINT TABLES_PK PRIMARY KEY (TID),
  				CONSTRAINT C_TABLE_ID_UNIQ UNIQUE (DB_ID, TABLE_NAME)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="5" type="index" name="IDX_TABLES_TID" dependsOn="TABLES">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX idx_tables_tid on TABLES (TID)]]></tns:sql>
			</tns:Object>
			<tns:Object order="6" type="index" name="IDX_TABLES_NAME" dependsOn="TABLES">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX idx_tables_name on TABLES (DB_ID, TABLE_NAME)]]></tns:sql>
			</tns:Object>
			<tns:Object order="7" type="table" name="COLUMNS">
				<tns:sql><![CDATA[
				CREATE TABLE COLUMNS (
  				TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  				COLUMN_NAME VARCHAR(128) NOT NULL,
  				ORDINAL_POSITION INTEGER NOT NULL,
  				DATA_TYPE CHAR(16),
  				TYPE_LENGTH INTEGER,
  				CONSTRAINT COLUMNS_PK PRIMARY KEY (TID, COLUMN_NAME)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="8" type="index" name="IDX_FK_COLUMNS_TABLE_NAME" dependsOn="COLUMNS">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX idx_fk_columns_table_name on COLUMNS (TID, COLUMN_NAME)]]></tns:sql>
			</tns:Object>
			<tns:Object order="9" type="table" name="OPTIONS">
				<tns:sql><![CDATA[
				CREATE TABLE OPTIONS (
  				TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  				KEY_ VARCHAR(255) NOT NULL,
  				VALUE_ VARCHAR(255) NOT NULL,
  				CONSTRAINT C_OPTIONS_UNIQUE UNIQUE (TID, KEY_, VALUE_)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="10" type="index" name="IDX_OPTIONS_KEY" dependsOn="OPTIONS">
				<tns:sql><![CDATA[CREATE INDEX idx_options_key on OPTIONS (TID)]]></tns:sql>
			</tns:Object>
			<tns:Object order="11" type="table" name="INDEXES">
				<tns:sql><![CDATA[
				CREATE TABLE INDEXES (
  				DB_ID INT NOT NULL REFERENCES DATABASES_ (DB_ID) ON DELETE CASCADE,
  				TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  				INDEX_NAME VARCHAR(128) NOT NULL,
  				COLUMN_NAME VARCHAR(128) NOT NULL,
  				DATA_TYPE VARCHAR(128) NOT NULL,
  				INDEX_TYPE CHAR(32) NOT NULL,
  				IS_UNIQUE BOOLEAN NOT NULL,
  				IS_CLUSTERED BOOLEAN NOT NULL,
  				IS_ASCENDING BOOLEAN NOT NULL,
  				CONSTRAINT C_INDEXES_PK PRIMARY KEY (DB_ID, INDEX_NAME)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="12" type="index" name="IDX_INDEXES_PK" dependsOn="INDEXES">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX idx_indexes_pk ON INDEXES (DB_ID,index_name)]]></tns:sql>
			</tns:Object>
			<tns:Object order="13" type="index" name="IDX_INDEXES_COLUMNS" dependsOn="INDEXES">
				<tns:sql><![CDATA[CREATE INDEX idx_indexes_columns ON INDEXES (DB_ID,column_name)]]></tns:sql>
			</tns:Object>
			<tns:Object order="14" type="table" name="STATS">
				<tns:sql><![CDATA[
				CREATE TABLE STATS (
  				TID INT NOT NULL PRIMARY KEY,
  				NUM_ROWS BIGINT,
  				NUM_BYTES BIGINT,
  				FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="15" type="index" name="IDX_STATS_TABLE_NAME" dependsOn="STATS">
				<tns:sql><![CDATA[CREATE UNIQUE INDEX IDX_STATS_TABLE_NAME ON STATS (TID)]]></tns:sql>
			</tns:Object>
			<tns:Object order="16" type="table" name="PARTITION_METHODS">
				<tns:sql><![CDATA[
				CREATE TABLE PARTITION_METHODS (
  				TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  				PARTITION_TYPE VARCHAR(10) NOT NULL,
  				EXPRESSION VARCHAR(1024) NOT NULL,
  				EXPRESSION_SCHEMA VARCHAR(1024) FOR BIT DATA NOT NULL
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="17" type="index" name="IDX_PARTITION_METHODS_TABLE_ID" dependsOn="PARTITION_METHODS">
				<tns:sql><![CDATA[CREATE INDEX idx_partition_methods_table_id ON PARTITION_METHODS (TID)]]></tns:sql>
			</tns:Object>
			<tns:Object order="18" type="table" name="TABLESPACES_HIST">
				<tns:sql><![CDATA[
				CREATE TABLE TABLESPACES_HIST (
  				SPACE_HIST_ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  				SPACE_NAME VARCHAR(128) NOT NULL CONSTRAINT SPACE_HIST_UNIQUE UNIQUE,
  				SPACE_HANDLER VARCHAR (1024) DEFAULT 'HDFS',
  				SPACE_URI VARCHAR (4096) NOT NULL,
  				CONSTRAINT C_SPACE_HIST_PK PRIMARY KEY (SPACE_HIST_ID)
				)]]>
				</tns:sql>
			</tns:Object>
			<tns:Object order="19" type="trigger" name="TABLESPACES_HIST_TRG">
				<tns:sql><![CDATA[
				CREATE TRIGGER TABLESPACES_HIST_TRG
				AFTER INSERT ON TABLESPACES
				REFERENCING NEW AS NEWROW
				FOR EACH ROW
				  INSERT INTO TABLESPACES_HIST
				  (SPACE_NAME, SPACE_URI)
				  VALUES
				  (NEWROW.SPACE_NAME, NEWROW.SPACE_URI)
				]]>
				</tns:sql>
			</tns:Object>
		</tns:objects>
	</tns:base>
	<tns:existQueries>
	  <tns:existQuery type="trigger">
	    <tns:sql><![CDATA[
	    select a.TRIGGERNAME from SYS.SYSTRIGGERS a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ?
	    ]]></tns:sql>
	  </tns:existQuery>
	  <tns:existQuery type="sequence">
	    <tns:sql><![CDATA[
	    select a.SEQUENCENAME from SYS.SYSSEQUENCES a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ?
	    ]]></tns:sql>
	  </tns:existQuery>
	  <tns:existQuery type="view">
	    <tns:sql><![CDATA[
	    select a.TABLENAME from SYS.SYSTABLES a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ? and a.TABLETYPE = 'V'
	    ]]></tns:sql>
	  </tns:existQuery>
	</tns:existQueries>	
</tns:store>

=== apache/tajo/tajo-catalog/tajo-catalog-server/src/test/resources/schemas/derbytest/querytest/derby.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<tns:store xmlns:tns="http://tajo.apache.org/catalogstore" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://tajo.apache.org/catalogstore ../../../../../main/resources/schemas/DBMSSchemaDefinition.xsd ">
	<tns:base version="1" schemaname="tajo">
		<tns:objects>
			<tns:Object order="0" type="table" name="TESTTABLE1">
				<tns:sql><![CDATA[CREATE TABLE TESTTABLE1 (COL1 INT, COL2 VARCHAR(10))]]></tns:sql>
			</tns:Object>
			<tns:Object order="1" type="index" name="TESTINDEX1" dependsOn="TESTTABLE1">
				<tns:sql><![CDATA[CREATE INDEX TESTINDEX1 ON TESTTABLE1 (COL1)]]></tns:sql>
			</tns:Object>
			<tns:Object order="2" type="table" name="TESTTABLE2">
				<tns:sql><![CDATA[CREATE TABLE TESTTABLE2 (COL1 INT, COL2 VARCHAR(10))]]></tns:sql>
			</tns:Object>
			<tns:Object order="3" type="trigger" name="TESTTRIGGER1">
				<tns:sql><![CDATA[
				CREATE TRIGGER TESTTRIGGER1
				AFTER INSERT ON TESTTABLE1
				REFERENCING NEW AS NEWROW
				FOR EACH ROW
				  INSERT INTO TESTTABLE2
				  (COL1, COL2)
				  VALUES
				  (NEWROW.COL1, NEWROW.COL2)
				]]></tns:sql>
			</tns:Object>
			<tns:Object order="4" type="sequence" name="TESTSEQ">
				<tns:sql><![CDATA[CREATE SEQUENCE TESTSEQ AS INT]]></tns:sql>
			</tns:Object>
			<tns:Object order="5" type="view" name="TESTVIEW">
				<tns:sql><![CDATA[CREATE VIEW TESTVIEW (TESTTEXT) AS VALUES 'Text1', 'Text2']]></tns:sql>
			</tns:Object>
		</tns:objects>
	</tns:base>
	<tns:existQueries>
	  <tns:existQuery type="trigger">
	    <tns:sql><![CDATA[
	    select a.TRIGGERNAME from SYS.SYSTRIGGERS a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ?
	    ]]></tns:sql>
	  </tns:existQuery>
	  <tns:existQuery type="sequence">
	    <tns:sql><![CDATA[
	    select a.SEQUENCENAME from SYS.SYSSEQUENCES a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ?
	    ]]></tns:sql>
	  </tns:existQuery>
	  <tns:existQuery type="view">
	    <tns:sql><![CDATA[
	    select a.TABLENAME from SYS.SYSTABLES a inner join SYS.SYSSCHEMAS b
           on a.SCHEMAID = b.SCHEMAID where b.SCHEMANAME = ? and a.TABLETYPE = 'V'
	    ]]></tns:sql>
	  </tns:existQuery>
	</tns:existQueries>
	<tns:dropStatements>
		<tns:dropStatement type="sequence">
			<tns:sql>DROP SEQUENCE ? RESTRICT</tns:sql>
		</tns:dropStatement>
	</tns:dropStatements>
</tns:store>

=== apache/tajo/tajo-catalog/tajo-catalog-server/src/main/resources/schemas/mariadb/mariadb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<tns:store xmlns:tns="http://tajo.apache.org/catalogstore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tajo.apache.org/catalogstore ../DBMSSchemaDefinition.xsd ">
  <!--
      Catalog base version history
      * 14 - 2016-05-10: Apply new type implementation to Schema and Catalog. (TAJO-2129)
      * 13 - 2016-05-07: Add some missing index to MariaDBStore (TAJO-2117)
      * 12 - 2015-09-28: Change the variable name storeType to dataFormat (TAJO-1663)
      * 11 - 2015-09-23: Add contents length and file count for partition directory (TAJO-1493)
      * 10 - 2015-09-22: Well support for self-describing data formats (TAJO-1832)
      * 9 - 2015-09-12: Allow external catalog store for unit testing (TAJO-1813)
      * 8 - 2015-09-02: Wrong table type problem in catalog (TAJO-1808)
      * 7 - 2015-07-30: Add a column and index for partition keys (TAJO-1346)
      * 6 - 2015-07-24: Merge the index branch into the master branch (TAJO-1300)
      * 5 - 2015-06-15: Implement TablespaceManager to load Tablespaces (TAJO-1616)
      * 4 - 2015-03-27: Partition Schema (TAJO-1284)
      * 3 - 2015-03-12: Nested Schema (TAJO-1329)
      * 2 - 2014-06-09: First versioning
      * 1-  Before 2013-03-20
    -->
  <tns:base version="13">
    <tns:objects>
      <tns:Object order="0" type="table" name="META">
        <tns:sql><![CDATA[CREATE TABLE META (VERSION INT NOT NULL)]]></tns:sql>
      </tns:Object>
      <tns:Object order="1" type="table" name="TABLESPACES">
        <tns:sql><![CDATA[
        CREATE TABLE TABLESPACES (
          SPACE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          SPACE_NAME VARCHAR(128) BINARY NOT NULL UNIQUE,
          SPACE_HANDLER VARCHAR (1024) DEFAULT 'HDFS',
          SPACE_URI VARCHAR (4096) BINARY NOT NULL,
          UNIQUE INDEX IDX_NAME (SPACE_NAME)
				)]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="2" type="table" name="DATABASES_">
        <tns:sql><![CDATA[
        CREATE TABLE DATABASES_ (
          DB_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          DB_NAME VARCHAR(128) BINARY NOT NULL UNIQUE,
          SPACE_ID INT NOT NULL,
          FOREIGN KEY (SPACE_ID) REFERENCES TABLESPACES (SPACE_ID),
          UNIQUE INDEX IDX_NAME (DB_NAME)
				)]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="3" type="table" name="TABLES">
        <tns:sql><![CDATA[
        CREATE TABLE TABLES (
          TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          DB_ID INT NOT NULL,
          TABLE_NAME VARCHAR(128) BINARY NOT NULL,
          TABLE_TYPE VARCHAR(128) NOT NULL,
          PATH VARCHAR(4096) BINARY,
          DATA_FORMAT CHAR(16),
          HAS_SELF_DESCRIBE_SCHEMA BOOLEAN,
          FOREIGN KEY (DB_ID) REFERENCES DATABASES_ (DB_ID),
          INDEX IDX_DB_ID (DB_ID),
          UNIQUE INDEX IDX_TABLE_ID (DB_ID, TABLE_NAME)
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="4" type="table" name="COLUMNS">
        <tns:sql><![CDATA[
        CREATE TABLE COLUMNS (
          TID INT NOT NULL,
          COLUMN_NAME VARCHAR(255) BINARY NOT NULL,
          ORDINAL_POSITION INT NOT NULL,
          DATA_TYPE VARCHAR(8192),
          PRIMARY KEY (TID, ORDINAL_POSITION),
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
        )]]>
        </tns:sql>
        <!--
		The constraint for guaranteeing the unique column name should be added to COLUMNS table. However, it can
		make this table's schema complicated due to nested fields. Fortunately, columns are always converted
		into 'schema' which has a functionality of checking duplicated column names.
		-->
      </tns:Object>
      <tns:Object order="5" type="table" name="OPTIONS">
        <tns:sql><![CDATA[
        CREATE TABLE OPTIONS (
          TID INT NOT NULL,
          KEY_ VARCHAR(255) BINARY NOT NULL,
          VALUE_ VARCHAR(4000) NOT NULL,
          PRIMARY KEY (TID, KEY_),
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="6" type="table" name="INDEXES">
        <tns:sql><![CDATA[
        CREATE TABLE INDEXES (
          INDEX_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          DB_ID INT NOT NULL,
          TID INT NOT NULL,
          INDEX_NAME VARCHAR(128) NOT NULL,
          INDEX_TYPE CHAR(32) BINARY NOT NULL,
          PATH VARCHAR(4096) NOT NULL,
          COLUMN_NAMES VARCHAR(255) NOT NULL, -- array of column names
          DATA_TYPES VARCHAR(128) NOT NULL, -- array of column types
          ORDERS VARCHAR(128) NOT NULL, -- array of column orders
          NULL_ORDERS VARCHAR(128) NOT NULL, -- array of null orderings
          IS_UNIQUE BOOLEAN NOT NULL,
          IS_CLUSTERED BOOLEAN NOT NULL,
          FOREIGN KEY (DB_ID) REFERENCES DATABASES_ (DB_ID) ON DELETE CASCADE,
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE,
          UNIQUE INDEX IDX_DB_ID_NAME (DB_ID, INDEX_NAME)
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="7" type="index" name="INDEXES_IDX_TID_COLUMN_NAME" dependsOn="INDEXES">
        <tns:sql><![CDATA[CREATE INDEX INDEXES_IDX_TID_COLUMN_NAME on INDEXES (DB_ID, TID, COLUMN_NAMES)]]></tns:sql>
      </tns:Object>
      <tns:Object order="8" type="table" name="STATS">
        <tns:sql><![CDATA[
        CREATE TABLE STATS (
          TID INT NOT NULL PRIMARY KEY,
          NUM_ROWS BIGINT,
          NUM_BYTES BIGINT,
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="9" type="table" name="PARTITION_METHODS">
        <tns:sql><![CDATA[
        CREATE TABLE PARTITION_METHODS (
          TID INT NOT NULL PRIMARY KEY,
          PARTITION_TYPE VARCHAR(10) NOT NULL,
          EXPRESSION VARCHAR(1024) NOT NULL,
          EXPRESSION_SCHEMA VARCHAR(1024) NOT NULL,
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="10" type="table" name="PARTITIONS">
        <tns:sql><![CDATA[
        CREATE TABLE PARTITIONS (
          PARTITION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
          TID INT NOT NULL,
          PARTITION_NAME VARCHAR(255) BINARY,
          PATH VARCHAR(4096) BINARY,
          NUM_BYTES BIGINT,
          UNIQUE INDEX PARTITION_UNIQUE_IDX (TID, PARTITION_NAME),
          FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
        )]]>
        </tns:sql>
      </tns:Object>
      <tns:Object order="11" type="table" name="PARTITION_KEYS">
        <tns:sql><![CDATA[
        CREATE TABLE PARTITION_KEYS (
          PARTITION_ID INT NOT NULL,
          TID INT NOT NULL,
          COLUMN_NAME VARCHAR(255) BINARY NOT NULL,
          PARTITION_VALUE VARCHAR(255) BINARY,
          INDEX PARTITION_KEYS_IDX (TID, COLUMN_NAME, PARTITION_VALUE),
          FOREIGN KEY (PARTITION_ID) REFERENCES PARTITIONS (PARTITION_ID) ON DELETE CASCADE
        )]]>
        </tns:sql>
      </tns:Object>
    </tns:objects>
  </tns:base>

</tns:store>
